"""create callback_log

Revision ID: a1b2c3d4e5f6
Revises:
Create Date: 2026-08-27

The PHR's raw archive of inbound ABDM callbacks -- see
aegle_phr/models.py:CallbackLog. Written by hand rather than autogenerated
so the JSONB and timestamptz choices are explicit.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "a1b2c3d4e5f6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "callback_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("callback_type", sa.Text(), nullable=False),
        sa.Column("request_id", sa.Text(), nullable=True),
        sa.Column("correlation_id", sa.Text(), nullable=True),
        # JSONB, not JSON: we will want to index and query into these
        # payloads once real handlers land in P3.
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_ip", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_callback_log"),
    )

    op.create_index("ix_callback_log_received_at", "callback_log", ["received_at"])
    op.create_index("ix_callback_log_request_id", "callback_log", ["request_id"])


def downgrade() -> None:
    op.drop_index("ix_callback_log_request_id", table_name="callback_log")
    op.drop_index("ix_callback_log_received_at", table_name="callback_log")
    op.drop_table("callback_log")
